from __future__ import annotations

import math

import numpy as np
import torch


def log_sphere_mgf(dimension: int, kappa: float) -> float:
    """Compute ``log E_Haar exp(kappa * mu.u)`` by the positive 0F1 series.

    Every term is non-negative, so the convergence test is monotone and does
    not suffer cancellation.  Production never substitutes an asymptotic or
    small-kappa approximation: a non-finite term or non-convergence fails
    closed.
    """

    dimension = int(dimension)
    kappa = float(kappa)
    if dimension < 2 or kappa < 0.0 or not math.isfinite(kappa):
        raise ValueError("dimension >= 2 and finite kappa >= 0 are required")
    if kappa == 0.0:
        return 0.0
    squared_quarter = 0.25 * kappa * kappa
    total = 1.0
    term = 1.0
    for order in range(1, 10000):
        term *= squared_quarter / (
            float(order) * (0.5 * float(dimension) + float(order) - 1.0)
        )
        total_next = total + term
        if not math.isfinite(term) or not math.isfinite(total_next):
            raise FloatingPointError(
                f"vMF normalizer series overflowed for dimension={dimension}, kappa={kappa}"
            )
        if term <= np.finfo(np.float64).eps * total_next:
            return math.log(total_next)
        total = total_next
    raise RuntimeError(
        f"vMF normalizer series failed to converge for dimension={dimension}, kappa={kappa}"
    )


def sample_wood_projection(
    dimension: int,
    kappa: float,
    count: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Draw Wood's exact axial cosine with the supplied NumPy stream.

    The resident CUDA sampler deliberately keeps this rejection step on the
    host.  Beta proposals and their rejection uniforms therefore have one
    explicit PCG64-only stream, while tangent normals are generated by an
    independent CUDA stream.
    """

    if int(dimension) < 2 or int(count) <= 0 or not math.isfinite(kappa) or kappa <= 0.0:
        raise ValueError("Wood projection requires dimension>=2, count>0, and finite kappa>0")
    p_minus_one = float(dimension - 1)
    # Rationalized Wood coefficient avoids subtracting two nearly equal
    # quantities when kappa is large (kappa_move = 80P in production).
    b = p_minus_one / (
        2.0 * kappa + math.sqrt(4.0 * kappa * kappa + p_minus_one * p_minus_one)
    )
    x0 = (1.0 - b) / (1.0 + b)
    c = kappa * x0 + p_minus_one * math.log1p(-(x0 * x0))
    projection = np.empty(int(count), dtype=np.float64)
    filled = 0
    alpha = 0.5 * p_minus_one
    iterations = 0
    while filled < int(count):
        iterations += 1
        if iterations > 10000:  # pragma: no cover - defensive fail-closed guard.
            raise RuntimeError("vMF rejection sampler failed to accept")
        draw = max(1024, int(math.ceil((count - filled) * 1.25)))
        beta = rng.beta(alpha, alpha, size=draw)
        candidate = (1.0 - (1.0 + b) * beta) / (1.0 - (1.0 - b) * beta)
        log_accept = (
            kappa * candidate
            + p_minus_one * np.log1p(-x0 * candidate)
            - c
        )
        accepted = candidate[np.log(rng.random(draw)) <= log_accept]
        take = min(accepted.size, count - filled)
        if take:
            projection[filled : filled + take] = accepted[:take]
            filled += take
    return projection


def _resident_standard_normal(
    shape: tuple[int, int],
    *,
    generator: torch.Generator,
    device: torch.device,
) -> torch.Tensor:
    return torch.randn(
        shape,
        generator=generator,
        device=device,
        dtype=torch.float64,
    )


def _resident_tangent(
    means_unit: torch.Tensor,
    *,
    generator: torch.Generator,
) -> torch.Tensor:
    """Draw normalized Gaussian tangents using only ``generator``.

    The zero-norm redraw branch is effectively measure zero, but is retained
    as a fail-safe exact implementation rather than silently accepting an
    invalid proposal.
    """

    count, dimension = means_unit.shape
    tangent = _resident_standard_normal(
        (int(count), int(dimension)),
        generator=generator,
        device=means_unit.device,
    )
    tangent = tangent - torch.sum(
        tangent * means_unit,
        dim=1,
        keepdim=True,
    ) * means_unit
    norms = torch.linalg.vector_norm(tangent, dim=1, keepdim=True)
    zero = norms[:, 0] == 0.0
    redraw_count = 0
    while bool(torch.any(zero).item()):
        redraw_count += 1
        if redraw_count > 10000:  # pragma: no cover - defensive fail-closed guard.
            raise RuntimeError("resident vMF tangent sampler failed to draw a nonzero tangent")
        indices = torch.nonzero(zero, as_tuple=False).reshape(-1)
        replacement = _resident_standard_normal(
            (int(indices.numel()), int(dimension)),
            generator=generator,
            device=means_unit.device,
        )
        selected_means = means_unit.index_select(0, indices)
        replacement = replacement - torch.sum(
            replacement * selected_means,
            dim=1,
            keepdim=True,
        ) * selected_means
        tangent = tangent.index_copy(0, indices, replacement)
        replacement_norms = torch.linalg.vector_norm(
            replacement,
            dim=1,
            keepdim=True,
        )
        norms = norms.index_copy(0, indices, replacement_norms)
        zero = norms[:, 0] == 0.0
    return tangent / norms


def sample_vmf_resident(
    mean: torch.Tensor,
    kappa: float,
    count: int,
    *,
    axial_rng: np.random.Generator,
    tangent_generator: torch.Generator,
) -> torch.Tensor:
    """Draw a resident FP64 vMF pool with domain-separated random streams."""

    direction = mean.reshape(-1)
    if direction.dtype != torch.float64:
        raise TypeError("resident vMF mean must use torch.float64")
    if direction.numel() < 2 or int(count) <= 0:
        raise ValueError("resident vMF requires dimension>=2 and count>0")
    norm = torch.linalg.vector_norm(direction)
    if not bool(torch.isfinite(norm).item()) or float(norm.item()) <= 0.0:
        raise ValueError("resident vMF mean must be finite and nonzero")
    direction = direction / norm
    concentration = float(kappa)
    if concentration < 0.0 or not math.isfinite(concentration):
        raise ValueError("resident vMF concentration must be finite and non-negative")
    if concentration <= 1.0e-12:
        values = _resident_standard_normal(
            (int(count), int(direction.numel())),
            generator=tangent_generator,
            device=direction.device,
        )
        norms = torch.linalg.vector_norm(values, dim=1, keepdim=True)
        if bool(torch.any(norms == 0.0).item()):
            raise FloatingPointError("zero Gaussian norm while sampling the resident Haar sphere")
        return values / norms
    projection = sample_wood_projection(
        int(direction.numel()),
        concentration,
        int(count),
        axial_rng,
    )
    means_unit = direction[None, :].expand(int(count), -1)
    tangent = _resident_tangent(means_unit, generator=tangent_generator)
    projection_tensor = torch.tensor(
        projection,
        device=direction.device,
        dtype=torch.float64,
    )
    return (
        projection_tensor[:, None] * means_unit
        + torch.sqrt(
            torch.clamp(1.0 - projection_tensor.square(), min=0.0)
        )[:, None]
        * tangent
    )


def sample_vmf_resident_batch(
    means: torch.Tensor,
    kappa: float,
    *,
    axial_rng: np.random.Generator,
    tangent_generator: torch.Generator,
) -> torch.Tensor:
    """Draw one local resident vMF proposal around every row of ``means``."""

    if means.ndim != 2 or means.shape[1] < 2:
        raise ValueError("resident vMF batch means must have shape (count, dimension>=2)")
    if means.dtype != torch.float64:
        raise TypeError("resident vMF batch means must use torch.float64")
    norms = torch.linalg.vector_norm(means, dim=1, keepdim=True)
    if not bool(torch.isfinite(norms).all().item()) or bool(torch.any(norms <= 0.0).item()):
        raise ValueError("resident vMF batch means must be finite and nonzero")
    means_unit = means / norms
    concentration = float(kappa)
    if concentration < 0.0 or not math.isfinite(concentration):
        raise ValueError("resident vMF concentration must be finite and non-negative")
    if concentration <= 1.0e-12:
        values = _resident_standard_normal(
            (int(means.shape[0]), int(means.shape[1])),
            generator=tangent_generator,
            device=means.device,
        )
        value_norms = torch.linalg.vector_norm(values, dim=1, keepdim=True)
        if bool(torch.any(value_norms == 0.0).item()):
            raise FloatingPointError("zero Gaussian norm while sampling the resident Haar sphere")
        return values / value_norms
    projection = sample_wood_projection(
        int(means.shape[1]),
        concentration,
        int(means.shape[0]),
        axial_rng,
    )
    tangent = _resident_tangent(means_unit, generator=tangent_generator)
    projection_tensor = torch.tensor(
        projection,
        device=means.device,
        dtype=torch.float64,
    )
    return (
        projection_tensor[:, None] * means_unit
        + torch.sqrt(
            torch.clamp(1.0 - projection_tensor.square(), min=0.0)
        )[:, None]
        * tangent
    )
